### ISSUE TITLE
Using vue filter loses reference to _

### ISSUE THREAD

**Issue by ottz0** [Ewocker/vue-lodash#12]
I can't seem to use the treeshaking with a vue filter as it loses reference to _. As I get an error _ is not defined in Vue. So I need to import the whole library in order for it to work. I tried also `this._.kebabCased `and it does not work

`Vue.use(VueLodash, { name: 'custom', lodash: { map, random, kebabCase } })`

```
Vue.filter('kebab', function (string) {
 return _.kebabCase(string);
})

```

**Comment by Ewocker** [comment]
From Evan's comment, filter should be pure functions and should not depends on this context.
https://github.com/vuejs/vue/issues/5998#issuecomment-311965292
