### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jdfx** [Ewocker/vue-lodash#2]
Does this package allow us to do use things like ._pull and Vue's reactivity will pick it up?

**Comment by Ewocker** [comment]
`let array = ['a', 'b', 'c', 'a', 'b', 'c']`
`this._.pull(array, 'a', 'c')`
`console.log(array)`

If this is something that you mean, then yes. "this._" works exactly like how you are using Lodash.

**Comment by rickbsgu** [comment]
Wierdness -- I can't get this to work in 'methods:' or 'compute:'.  'this._' comes up undefined (not using arrow functions -- it sees this.(otherstuff)  fine.)

It _does_ work in the lifestyle hooks ('created()').

I'm looking at webpack as a possible culprit, but that shouldn't affect the dev environment, I wouldn't think...

**Comment by Ewocker** [comment]
Pretty sure you might have missed out something. I am using both webpack advance ad webpack simple with this in my created cycle hook as template and it seems to work fine.
If this is still a problem, can you provide more details on your setup such that I might be able to help.

**Comment by jdfx** [comment]
Thanks, but the initial question was about reactivity.

It's been a while since I looked at this but if I remember correctly VueJS's reactivity doesnt play well with Lodash - I was asking if this project fixes that?

For example if I modify a piece of data using _.pulll() a computed property using that data would not update - as VueJS does not listen to Lodash's _.pull() - it is bound on the native splice().

You can see people talking about it here:

https://forum.vuejs.org/t/computed-properties-not-updating-when-using-lodash-and-vuejs/6133
