### ISSUE TITLE
Dose vue-lodash support vue3?

### ISSUE THREAD

**Issue by SonicMiso** [Ewocker/vue-lodash#27]
I am a Front-end novice developer and after install vue-lodash I still got a error that _ is undefined(with a right 'this' scope).So I wonder if this plugin is not suitable for vue3 or just blame to my inexperiencing?

**Comment by rmcdaniel** [comment]
No, it doesn't work for Vue3.

**Comment by SonicMiso** [comment]
> No, it doesn't work for Vue3.

Ok,I see.Thank you.
