### ISSUE TITLE
how to use it globally

### ISSUE THREAD

**Issue by yangtoude** [Ewocker/vue-lodash#4]
I found that i use it in the entry file main.js:

```
import VueLodash from 'vue-lodash'

Vue.use(VueLodash, {name: 'lodash'})

new Vue({})
```

but i can't use it in the subcomponent:
```
import Vue from 'vue'

export default {
  methods: {
    getSomething: Vue._.debounce(
//    getSomething: this._.debounce( // not work either
      function() {
        // some codes
      },
      1000
    )
  }
}
```
the browser throwed an error:
```
Uncaught TypeError: Cannot read property 'debounce' of undefined
```

and i have to import it in the subcomponent:
```
import VueLodash from 'vue-lodash'
Vue.use(VueLodash, {name: '_'})

export default {
 // 
}
```
Do I have any problems with the code I wrote ? And is there any way to use this plugin globally?

**Comment by Ewocker** [comment]
Hi @yangtoude.
There is a similar issue with this, the scope of Vue is not accessible with your current way of using it.
Please check #3 . Thanks!

**Comment by yangtoude** [comment]
Ok, I think I've got it. Thanks, @Ewocker !
