### ISSUE TITLE
How to load individual functions?

### ISSUE THREAD

**Issue by FreddyCrugger** [Ewocker/vue-lodash#8]
Hello,

It looks like your plugin loads every functions from Lodash is there a way to load only the functions we need to increase the speed of the app?

Thank you.

**Comment by Ewocker** [comment]
Not at this moment, I would suggest you to import only the lodash module that you need instead of using this plugin in this case.

**Comment by FreddyCrugger** [comment]
Thank you for the reply.
Ok I will do that.
